language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- deploy
branches:
  only:
  - master
env:
  global:
  - secure: NkXi46Nv25UltyZum8nLlVEH4usa1d038jDUyW7hb80NRDR4bW6ps9CQnIRQEDczwt3g5wHhuf/xT2XPBp4uh3Pz5UsqCwhoahZPykT2YA22yfQ8fhKHNFaIwEacJi952670968LIxxV/+ra4s8j7PyTZIzlziYnIs6N7w8sM63Oq6VAn17/OG4OIqDJN8ieYvc/OTAJ841JZFt0T4iQLCnC5V3FApUBs0EGVAXeVZD36cXizEwOK1mecbkpX8IV17QrWVmVzC+EFwyNdBwzbkbKmFM/dov6DJVpu8zaZpB62CW5XWIPPRVasZzJ9U/Fe+lqZQHQJdZMqdgEDHfdRCvqFhyA8wjPdC9NTnXSMv5T0M8GmQW2qeaZgz9uH/uvXDj5H0B/PjLGGsGw2vN48Tu3QGctGn4NU9SKibCocc5Jf3SxSvUNZ+nhSx7/iTpvO6oji22eHZ//a358S0zfxvvauC/WgISP3Y4NsdmPs6yMRxiE27VwgpXeAD2ZskA829MQnfX4f4y5+GniTuk2d7I9bBeKdRcRg+qKh5Lt7rvLPKJjWYCOJIkf80jPjY65LKe2jigk+PmZ9+tE7FrJeElv95pn1xjbMYZOPA9mJ2Ta3DXr9kgilV/IgEDMqtnDfx0kJpFa4xKEqCH6jNlruiDNU0bt01D76VeRarE7UA8=
  - secure: HBI0cazT55g7Ta8AIRwLY/0U1TVjG0d2TP2601NsX0uvA3mqTcJNIWcjij51+p2YL8tzXn4Wg40/6D0j2xv4BzyAcXC3X6i1fCy1fAuFp6FZMmAI3fBDV2QDfBiFaaEeOhwU9WR5mGmHUeLDpKZ9LURSyDmtUKHPSIlb8mwH0+sNEnS5iuXSLNDw70oVyEYe1dIerNXFCE4SVrKcyjIihQP17cSDjXXQRJ17tf9Rbmkmgllfu2gaCcyB4k+h4dEhm1Cs8qJ6Jh0BYLNSLTrFIHfDwy+FlQg7j1PuBYA8PIfAu1NHoIYB4T17dT9wUtL1Vk4EofIDxXWqr+pHl5VVdJoHxlSlX+EnfNzh67yPXIhdMkPv4VzHPdQdKCy+/Sblzxo/m1Lau1WVxls5PGpuZfyrfnmFjcBQ1ZCJwhE6VsWyT6DDBtsR++zAH1SHNfswyl5FsnApxnH7q656QUSVK9AO7pSevM0lOpEp69123RyO/U3BjoDuro88ENxaPR23vmGgYGE/KwVQhNAiYzigfYI4tdviA1Qw8uCqm4jvnzOreUvvxl5gJlS6+NJ3jJrD3t4taK1h54C4655ruynvEsLKSxzkeK6zeLGoSDIOo2zERVK0GvVb9e6woiYN33RdhJgQxLF+9lprx35GGgFoy+60C5uXE/tvNV1gBWiVsAw=
