language: go
install:
- go get -v github.com/spf13/hugo
- pip install --user awscli
script:
- hugo version
- make deploy
branches:
  only:
  - master
env:
  global:
  - secure: a60+ghzwV+Zpc7kp4QUdrR6gA5NAbC9jo1VnSqa7bqwbvfszkWoo4GET28y73ynWqr1cHMo7vmehsZZT8gb0dVe+bl/j6ukq+vaCKpo4Tl8Vame6goC/gkwd5neYNCFT6jZ+m51a436bU9hn5KAzDtuQOuNKzlQ4qpwviCIgTWI6BjAkaexy2XBCGZPl/r2mHaDGfy8eebOilQ53qUSQ4fD8C1glTa/0y1ob68rb5cNZUR5HNZwhrPhQSsFNyhZOt8T3cdjfuVSI1Q6WhnkL3Z6MO83gwbvqtHt7jps7fSJburOszpVyXA1KSOuyYaHgqM4akCUpNP1JjVvA5KJqUWy65q/y/APyFOCMhqgceZttTOp/+3N9VUuPqvSPKNhFP55RK6YExm7FVKIv2uWqixi+qTwfk7Qiun27d4pNyKeVPT29jf2xdJfwx7Qw6BN5FX9D3yn+DoknuHkWNoNplu17HK/1d5Onw3V46wpNCVsdaw/9yVSAt+8mPOEloPAqkINJgCr0Ay630/B4+wGtxNNaqOP/K5bJsb5wTwKfbdaCphL/uOQtzaLbu0bhPTz4uyHQFDhq/8w0hkZWAxj6mbDE7VPAzzEbPW1Y/qy13DW0h9ossm6LYn/IY0wljUp5sL+lhGDefubXBbhEDbEGWH2Uo/XZJoxPzh9NtqjtU2s=
  - secure: Mo+0dCqTbSsGAnlVolrwOKUTsUokpfyxoOJZu2kfHlOyozpVc4vP3/vhzYvqa7IJBsMIP/d2Tex1tPbXHMPX/35jKvjw1DaQ213ssSMs+sUDJ7DyIcz8JuzXYYI7+MY0yvLMc5vE18FNDHlkWwn1Kn72OJa/UpRy2BqydAsV40SjxjpEsW75Sb1qhl0PNVFxafE2i8p+ZMHEdZXtD7buJIM4obIM9Gy5fP1rZ3okolONUJRlON7LF0s9l5idFv81yDzvIQ3d7MyuiI1szkiJjnYwvztW6n4A2aKcq+X5KpPFYsksh3wynaOkbAowxAP2rO9j/bgzaqdLj+Ay3uYsm7wijTEW4UhPjz6pJ3lJxXwaGmJcgaPheELDduawdYeqlmNCGHr4cTyBldDIUqiIgVYz1evqb1jcTMAjs3A9FURRBaeypFwLW34JrfLEjSc3EQjU/qg/gVPdtBD2Tx5DruwkglQTOI0/WRkeIAWpDG5irxw00q1Kr4jb0/zfdOasoXDirku6Yk+FGWYleufGzMgYcopfk9/t7NPb2mjpOUC0ZE/230JbljZ7dlWr1hBvvGxp6xKT85ANxeUterry5tnRLaazbryY7ytWqvFsihSZJ+3Uz1caDFjaDNgpg06jV47SW1+4Za5eeAML+3Ef3LMY/4G+KqQJsFd603jKwlc=
